config/routes.rb
Rails.application.routes.draw do
  resources :clients

  resources :deployments

  resources :jobs

  resources :users

  resources :charges

  resources :batteries

   root 'batteries#index'

end

app/models/charge.rb
class Charge < ActiveRecord::Base
  belongs_to :battery
  belongs_to :user
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  before_action :set_charge, only: [:show, :edit, :update, :destroy]

  # GET /charges
  # GET /charges.json
  def index
    @charges = Charge.all
  end

  # GET /charges/1
  # GET /charges/1.json
  def show
  end

  # GET /charges/new
  def new
    @charge = Charge.new
  end

  # GET /charges/1/edit
  def edit
  end

  # POST /charges
  # POST /charges.json
  def create
    @charge = Charge.new(charge_params)

    respond_to do |format|
      if @charge.save
        format.html { redirect_to @charge, notice: 'Charge was successfully created.' }
        format.json { render :show, status: :created, location: @charge }
      else
        format.html { render :new }
        format.json { render json: @charge.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /charges/1
  # PATCH/PUT /charges/1.json
  def update
    respond_to do |format|
      if @charge.update(charge_params)
        format.html { redirect_to @charge, notice: 'Charge was successfully updated.' }
        format.json { render :show, status: :ok, location: @charge }
      else
        format.html { render :edit }
        format.json { render json: @charge.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /charges/1
  # DELETE /charges/1.json
  def destroy
    @charge.destroy
    respond_to do |format|
      format.html { redirect_to charges_url, notice: 'Charge was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_charge
      @charge = Charge.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def charge_params
      params.require(:charge).permit(:battery_id, :charge_date, :voltage, :user_id)
    end
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/views/charges/_form.html.erb
<%= form_for(@charge) do |f| %>
  <% if @charge.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@charge.errors.count, "error") %> prohibited this charge from being saved:</h2>

      <ul>
      <% @charge.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :battery_id %><br>
    <%= f.text_field :battery_id %>
  </div>
  <div class="field">
    <%= f.label :charge_date %><br>
    <%= f.date_select :charge_date %>
  </div>
  <div class="field">
    <%= f.label :voltage %><br>
    <%= f.text_field :voltage %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/charges/edit.html.erb
<h1>Editing charge</h1>

<%= render 'form' %>

<%= link_to 'Show', @charge %> |
<%= link_to 'Back', charges_path %>

app/views/charges/index.html.erb
<h1>Listing charges</h1>

<table>
  <thead>
    <tr>
      <th>Battery</th>
      <th>Charge date</th>
      <th>Voltage</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @charges.each do |charge| %>
      <tr>
        <td><%= charge.battery_id %></td>
        <td><%= charge.charge_date %></td>
        <td><%= charge.voltage %></td>
        <td><%= charge.user_id %></td>
        <td><%= link_to 'Show', charge %></td>
        <td><%= link_to 'Edit', edit_charge_path(charge) %></td>
        <td><%= link_to 'Destroy', charge, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Charge', new_charge_path %>

app/views/charges/new.html.erb
<h1>New charge</h1>

<%= render 'form' %>

<%= link_to 'Back', charges_path %>

app/views/charges/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Battery:</strong>
  <%= @charge.battery_id %>
</p>

<p>
  <strong>Charge date:</strong>
  <%= @charge.charge_date %>
</p>

<p>
  <strong>Voltage:</strong>
  <%= @charge.voltage %>
</p>

<p>
  <strong>User:</strong>
  <%= @charge.user_id %>
</p>

<%= link_to 'Edit', edit_charge_path(@charge) %> |
<%= link_to 'Back', charges_path %>